name: CI

on: [push]

jobs:
  build:
    name: ${{ matrix.configname }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            configname: yfrm-win64-tracker-vulkan
          - os: windows-latest
            configname: yfrm-win64-angle-vulkan
          - os: windows-latest
            configname: yfrm-win64-angle-dx11
          - os: windows-latest
            configname: em2c-winstore-angle-dx11
          - os: windows-latest
            configname: em2c-win64-tracker-vulkan
          - os: windows-latest
            configname: em2c-win64-angle-dx11
          - os: macos-latest
            configname: em2c-ios-gles
          - os: macos-latest
            configname: em2c-mac-angle-metal
          - os: macos-latest
            configname: em2c-tvos-gles
          - os: ubuntu-latest
            configname: yfrm-posix-gles
          - os: ubuntu-latest
            configname: yfrm-posix-angle-vulkan
          - os: ubuntu-latest
            configname: android-sdl
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: ashutoshvarma/setup-ninja@66ad2db9ed7d211c065daeeb849e9c8c895773c9
        with:
          dest: ${{ github.workspace }}/ninja_bin
      - uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows-latest'
      - name: Setup additional packages
        run: cmake -DOS=${{ matrix.os }} -DCONFIG=${{ matrix.configname }}  -P cfg/_ghactionprepare.cmake
      - name: Prepare
        run: cmake -P cfg/_prepare.cmake
      - name: Build
        run: cmake -DCONFIG=${{ matrix.configname }} -P cfg/_all.cmake

